### ISSUE TITLE
Can not import capstone library

### ISSUE THREAD

**Issue by famasoon** [Cisco-Talos/pyrebox#81]
## Reproducing steps
Reproduce in the following steps.

```sh
$ docker build . -t pyrebox
$ docker run -it pyrebox
root@01c0bfa359a7:/pyrebox# ./start_i386.sh 

[*] Loading python component initialization script
[*] Platform: i386-softmmu
[*] Starting python module initialization
[*] Reading configuration from 'pyrebox.conf'
Traceback (most recent call last):
  File "/pyrebox/pyrebox/init.py", line 253, in init
    from ipython_shell import initialize_shell
  File "/pyrebox/pyrebox/ipython_shell.py", line 47, in <module>
    from capstone import Cs
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 315, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```

## Findings
In `Dockerfile`, `libcapstone.so` has moved directory.
So it seems python can not import library.

```
RUN mv /usr/local/lib/python2.7/dist-packages/capstone/lib/libcapstone.so /usr/local/lib
```

**Comment by xabiugarte** [comment]
Merged, thanks for the pull request!
